import js from '@eslint/js';
import vue from 'eslint-plugin-vue';

export default [
  js.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        CustomEvent: 'readonly',
        alert: 'readonly',
        btoa: 'readonly',
        Chart: 'readonly'
      }
    },
    rules: {
      'no-console': 'error',
      'no-debugger': 'error',
      'no-unused-vars': ['error', { 'vars': 'all', 'args': 'all', 'ignoreRestSiblings': false, 'argsIgnorePattern': '^_' }],
      'vue/no-unused-vars': 'error',
      'vue/multi-word-component-names': 'off',
      'vue/require-v-for-key': 'error',
      'vue/no-use-v-if-with-v-for': 'error',
      'vue/no-unused-components': 'error',
      'vue/require-default-prop': 'error',
      'vue/require-prop-types': 'error',
      'vue/no-required-prop-with-default': 'error',
      'vue/max-attributes-per-line': ['error', { singleline: 3, multiline: 1 }],
      'vue/html-self-closing': ['error', { html: { void: 'never' }, svg: 'always', math: 'always' }],
      'vue/v-slot-style': ['error', { atComponent: 'v-slot', default: 'v-slot' }],
      'vue/html-indent': ['error', 2],
      'vue/multiline-html-element-content-newline': 'error',
      'vue/singleline-html-element-content-newline': 'error',
      'vue/attributes-order': 'error',
      'vue/attribute-hyphenation': 'error',
      'vue/v-on-event-hyphenation': 'error',
      'vue/html-quotes': ['error', 'double'],
      'vue/order-in-components': 'error',
      'no-dupe-keys': 'error',
      'vue/no-dupe-keys': 'error',
      'no-undef': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-prototype-builtins': 'error',
      'no-empty': ['error', { 'allowEmptyCatch': true }],
      'no-case-declarations': 'error',
      'no-unreachable': 'error',
      'no-useless-escape': 'error',
      'vue/no-parsing-error': 'error',
      'vue/require-explicit-emits': 'error',
      'vue/no-v-html': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'brace-style': ['error', '1tbs'],
      'comma-dangle': ['error', 'never'],
      'semi': ['error', 'always'],
      'quotes': ['error', 'single'],
      'indent': ['error', 2],
      'no-trailing-spaces': 'error',
      'eol-last': 'error',
      'no-multiple-empty-lines': ['error', { max: 1 }],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'space-before-function-paren': ['error', 'never'],
      'keyword-spacing': 'error',
      'space-infix-ops': 'error',
      'no-multi-spaces': 'error',
      'no-shadow': 'error',
      'no-redeclare': 'error',
      'no-magic-numbers': ['error', { 'ignore': [0, 1, -1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 50, 100, 500, 1000] }],
      'complexity': ['error', 20],
      'max-lines-per-function': ['error', 100],
      'max-params': ['error', 6],
    }
  },
  {
    files: ['src/utils/constants.js'],
    rules: {
      'no-magic-numbers': 'off'
    }
  }
];