// HTTP Status Codes
const HTTP_OK = 200;
const HTTP_BAD_REQUEST = 400;
const HTTP_NOT_FOUND = 404;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_MOVED_PERMANENTLY = 301;

// Other constants
const DEFAULT_LIMIT = 20;
const MAX_LIMIT = 1000000;
const SERVER_PORT = 3000;

module.exports = {
  HTTP_OK,
  HTTP_BAD_REQUEST,
  HTTP_NOT_FOUND,
  HTTP_INTERNAL_SERVER_ERROR,
  HTTP_MOVED_PERMANENTLY,
  DEFAULT_LIMIT,
  MAX_LIMIT,
  SERVER_PORT
};